"""add user id to applications

Revision ID: ba0794f3df4d
Revises: 
Create Date: 2026-10-08 15:10:19.820924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba0794f3df4d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_applications_user_id'), 'applications', ['user_id'], unique=False)
    op.create_foreign_key(
    'fk_applications_user_id_users',
    'applications',
    'users',
    ['user_id'],
    ['id']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(
    'fk_applications_user_id_users',
    'applications',
    type_='foreignkey'
    )
    op.drop_index(op.f('ix_applications_user_id'), table_name='applications')
    op.drop_column('applications', 'user_id')
    # ### end Alembic commands ###
